[package]
name = "deep-learning-lib"
version = "0.1.0"
edition = "2024"

[lib]
name = "bbgrad"
path = "src/lib.rs"

[dependencies]
ndarray = { version = "0.17.2", features = ["blas"] }
ndarray-rand = "0.16.0"
